In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale 
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV
from sklearn.metrics import mean_squared_error

from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams

# Gets the box score of every single game (NBA + WNBA + others: nba.com doesn't seperate the leagues) 
# from 2014-2021 into a dataframe.
all_games_finder = leaguegamefinder.LeagueGameFinder()
all_games = all_games_finder.get_data_frames()[0]

# Creates empty dataframe with the same column names passed in from the dataframe containing all the games.
column_names = all_games.columns
games = pd.DataFrame(columns = column_names)

# Appends every game containing an NBA team in the all_games df to the games df. 
nba_teams = teams.get_teams()
for team in nba_teams:
    temp_id = team['id']
    games = games.append(all_games[all_games['TEAM_ID'] == temp_id])

pd.set_option('display.max_columns', None)
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
14,22021,1610612737,ATL,Atlanta Hawks,0022100319,2021-12-01,ATL @ IND,W,240,114,44,86,0.512,16,33,0.485,10,12,0.833,7,34,41,24,4,8,13,15,3.0
100,22021,1610612737,ATL,Atlanta Hawks,0022100293,2021-11-27,ATL vs. NYK,L,240,90,33,93,0.355,9,37,0.243,15,20,0.750,13,39,52,18,8,6,6,17,-9.0
116,22021,1610612737,ATL,Atlanta Hawks,0022100285,2021-11-26,ATL @ MEM,W,239,132,52,89,0.584,13,27,0.481,15,21,0.714,9,40,49,33,8,5,12,15,32.0
172,22021,1610612737,ATL,Atlanta Hawks,0022100277,2021-11-24,ATL @ SAS,W,239,124,45,88,0.511,12,26,0.462,22,24,0.917,8,36,44,26,10,5,9,11,18.0
197,22021,1610612737,ATL,Atlanta Hawks,0022100255,2021-11-22,ATL vs. OKC,W,239,113,42,87,0.483,14,34,0.412,15,16,0.938,8,36,44,25,6,6,7,16,12.0

In [2]:
# Dropping any game (two rows in DF) that has any NaN values or is missing either team's stats
games.isna()
games.dropna(inplace=True)

games = games[games.duplicated(subset = ['GAME_ID'], keep=False)]

# Merging games together (previously seperated in the DF by team: each team's stats from the game were kept in seperate rows
games = games.sort_values(by=['GAME_ID'])
games = games.reset_index(drop=True)

# Team A and B each have a row for their stats in a given matchup; we need to add both stats to the end of their respective rows
# Team A dataframe
tempA = games[games.index % 2 == 0]
tempA2 = games[games.index % 2 == 1]

tempA2 = tempA2.add_prefix('OPP_')

tempA = tempA.reset_index(drop=True)
tempA2 = tempA2.reset_index(drop=True)

a_temp = tempA.join(tempA2)

# Team B dataframe
tempB = games[games.index % 2 == 0]
tempB2 = games[games.index % 2 == 1]

tempB = tempB.add_prefix('OPP_')

tempB = tempB.reset_index(drop=True)
tempB2 = tempB2.reset_index(drop=True)

b_temp = tempB2.join(tempB)

# Adding both teams to main dataframe
games = a_temp.append(b_temp)

# Resorting main dataframe
games = games.sort_values(by=['GAME_ID'])
games = games.reset_index(drop=True)

# Sending data to CSV
games.to_csv('games.csv', index = False)



# Print Head
pd.set_option('display.max_columns', None)
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,OPP_SEASON_ID,OPP_TEAM_ID,OPP_TEAM_ABBREVIATION,OPP_TEAM_NAME,OPP_GAME_ID,OPP_GAME_DATE,OPP_MATCHUP,OPP_WL,OPP_MIN,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PLUS_MINUS
0,12015,1610612746,LAC,LA Clippers,0011500001,2015-10-02,LAC vs. DEN,W,238,103,37,91,0.407,9,32,0.281,20,26,0.769,9,30,39,22,12,6,13,15,7.0,12015,1610612743,DEN,Denver Nuggets,0011500001,2015-10-02,DEN @ LAC,L,240,96,37,87,0.425,7,18,0.389,15,20,0.750,14,43,57,16,9,2,23,26,-7.0
1,12015,1610612743,DEN,Denver Nuggets,0011500001,2015-10-02,DEN @ LAC,L,240,96,37,87,0.425,7,18,0.389,15,20,0.750,14,43,57,16,9,2,23,26,-7.0,12015,1610612746,LAC,LA Clippers,0011500001,2015-10-02,LAC vs. DEN,W,238,103,37,91,0.407,9,32,0.281,20,26,0.769,9,30,39,22,12,6,13,15,7.0
2,12015,1610612766,CHA,Charlotte Hornets,0011500002,2015-10-03,CHA @ ORL,W,241,106,34,75,0.453,12,31,0.387,26,35,0.743,7,34,41,30,7,2,13,15,6.0,12015,1610612753,ORL,Orlando Magic,0011500002,2015-10-03,ORL vs. CHA,L,240,100,39,89,0.438,6,26,0.231,16,19,0.842,12,33,45,22,11,3,12,30,-6.0
3,12015,1610612753,ORL,Orlando Magic,0011500002,2015-10-03,ORL vs. CHA,L,240,100,39,89,0.438,6,26,0.231,16,19,0.842,12,33,45,22,11,3,12,30,-6.0,12015,1610612766,CHA,Charlotte Hornets,0011500002,2015-10-03,CHA @ ORL,W,241,106,34,75,0.453,12,31,0.387,26,35,0.743,7,34,41,30,7,2,13,15,6.0
4,12015,1610612740,NOP,New Orleans Pelicans,0011500003,2015-10-03,NOP @ IND,W,242,110,37,103,0.359,11,32,0.344,25,37,0.676,19,36,55,16,9,3,11,22,5.0,12015,1610612754,IND,Indiana Pacers,0011500003,2015-10-03,IND vs. NOP,L,241,105,38,92,0.413,10,35,0.286,19,31,0.613,18,44,62,21,10,16,19,27,-5.0

In [3]:
temp_games = pd.DataFrame()
nba_teams = teams.get_teams()
for team in nba_teams:
    temp_id = team['id']
    temp_games = temp_games.append(games[games['TEAM_ID'] == temp_id])

games = temp_games
games_averages = games.copy() #Sets a copy to be used when we do rolling averages

# Print Head
pd.set_option('display.max_columns', None)
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,OPP_SEASON_ID,OPP_TEAM_ID,OPP_TEAM_ABBREVIATION,OPP_TEAM_NAME,OPP_GAME_ID,OPP_GAME_DATE,OPP_MATCHUP,OPP_WL,OPP_MIN,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PLUS_MINUS
29,12015,1610612737,ATL,Atlanta Hawks,0011500017,2015-10-07,ATL @ CLE,W,238,98,33,75,0.440,7,24,0.292,25,30,0.833,9,37,46,17,8,2,17,19,2.0,12015,1610612739,CLE,Cleveland Cavaliers,0011500017,2015-10-07,CLE vs. ATL,L,239,96,35,83,0.422,14,37,0.378,12,15,0.800,7,32,39,28,10,7,17,29,-2.0
53,12015,1610612737,ATL,Atlanta Hawks,0011500032,2015-10-09,ATL @ NOP,W,240,103,33,74,0.446,11,26,0.423,26,36,0.722,5,43,48,21,8,5,16,23,10.0,12015,1610612740,NOP,New Orleans Pelicans,0011500032,2015-10-09,NOP vs. ATL,L,238,93,32,84,0.381,7,27,0.259,22,31,0.710,6,38,44,15,8,7,13,26,-10.0
102,12015,1610612737,ATL,Atlanta Hawks,0011500060,2015-10-14,ATL vs. SAS,W,240,100,32,78,0.410,11,31,0.355,25,29,0.862,3,45,48,24,10,4,16,26,14.0,12015,1610612759,SAS,San Antonio Spurs,0011500060,2015-10-14,SAS @ ATL,L,240,86,27,82,0.329,4,20,0.200,28,36,0.778,11,39,50,17,9,2,18,25,-14.0
119,12015,1610612737,ATL,Atlanta Hawks,0011500068,2015-10-16,ATL @ DAL,W,241,91,31,84,0.369,9,28,0.321,20,24,0.833,9,40,49,18,9,7,15,14,7.0,12015,1610612742,DAL,Dallas Mavericks,0011500068,2015-10-16,DAL vs. ATL,L,241,84,31,85,0.365,9,33,0.273,13,17,0.765,8,41,49,18,8,6,18,19,-7.0
142,12015,1610612737,ATL,Atlanta Hawks,0011500081,2015-10-18,ATL vs. MIA,L,240,92,33,75,0.440,6,22,0.273,20,22,0.909,8,36,44,23,6,9,22,24,-9.0,12015,1610612748,MIA,Miami Heat,0011500081,2015-10-18,MIA @ ATL,W,240,101,36,92,0.391,10,30,0.333,19,25,0.760,15,29,44,26,8,2,13,16,9.0

In [4]:
# Storing some columns for future use
game_ids = games['GAME_ID'].values
team_ids = games['TEAM_ID'].values
minutes = games['MIN'].values
abrv = games['TEAM_ABBREVIATION'].values
spread = games['PLUS_MINUS'].values

# Dropping Non-essential categorical data
games = games.drop(columns=['SEASON_ID', 'OPP_SEASON_ID', 'OPP_TEAM_ID','GAME_ID', 'OPP_GAME_ID', 'TEAM_ABBREVIATION', 'OPP_TEAM_ABBREVIATION', 'TEAM_NAME', 'OPP_TEAM_NAME', 'MATCHUP', 'OPP_MATCHUP', 'WL', 'OPP_WL', 'GAME_DATE', 'OPP_GAME_DATE', 'MIN', 'OPP_MIN']) 

# Adding minutes back as a single column
games['MIN'] = minutes

# Print Head
pd.set_option('display.max_columns', None)
games.head()

,TEAM_ID,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PLUS_MINUS,MIN
29,1610612737,98,33,75,0.440,7,24,0.292,25,30,0.833,9,37,46,17,8,2,17,19,2.0,96,35,83,0.422,14,37,0.378,12,15,0.800,7,32,39,28,10,7,17,29,-2.0,238
53,1610612737,103,33,74,0.446,11,26,0.423,26,36,0.722,5,43,48,21,8,5,16,23,10.0,93,32,84,0.381,7,27,0.259,22,31,0.710,6,38,44,15,8,7,13,26,-10.0,240
102,1610612737,100,32,78,0.410,11,31,0.355,25,29,0.862,3,45,48,24,10,4,16,26,14.0,86,27,82,0.329,4,20,0.200,28,36,0.778,11,39,50,17,9,2,18,25,-14.0,240
119,1610612737,91,31,84,0.369,9,28,0.321,20,24,0.833,9,40,49,18,9,7,15,14,7.0,84,31,85,0.365,9,33,0.273,13,17,0.765,8,41,49,18,8,6,18,19,-7.0,241
142,1610612737,92,33,75,0.440,6,22,0.273,20,22,0.909,8,36,44,23,6,9,22,24,-9.0,101,36,92,0.391,10,30,0.333,19,25,0.760,15,29,44,26,8,2,13,16,9.0,240

In [5]:
# Adding Advanced Stats to enhance model performance, formulas were gathered from various sources. 

# Efficient Field Goal Percentage
games['EFG%'] = (games['FGM'] + (.5 * games['FG3M'])) / games['FGA']
games['OPP_EFG%'] = (games['OPP_FGM'] + (.5 * games['OPP_FG3M'])) / games['OPP_FGA']

# Block Percentage
games['BLK%'] = (games['BLK'] / (games['OPP_FGA']-games['OPP_FG3A']))
games['OPP_BLK%'] = (games['OPP_BLK'] / (games['FGA']-games['FG3A']))

# Turnover Percentage
games['TOV%'] = games['TOV'] / (games['FGA'] + 0.44 * games['FTA'] + games['TOV'])
games['OPP_TOV%'] = games['OPP_TOV'] / (games['OPP_FGA'] + 0.44 * games['OPP_FTA'] + games['OPP_TOV'])

#Offensive Rebound Percentage
games['ORB%'] = games['OREB'] / (games['OREB'] + games['OPP_DREB'])
games['OPP_ORB%'] = games['OPP_OREB'] / (games['OPP_OREB'] + games['DREB'])

#Defensive Rebound Percentage
games['DREB%'] = games['DREB'] / (games['OPP_OREB'] + games['DREB'])
games['OPP_DREB%'] = games['OPP_DREB'] / (games['OREB'] + games['OPP_DREB'])

# Possessions
#games["POSS"] = 0.5*((games["FGA"] + 0.4*games["FTA"] - 1.07*(games["OREB"]/(games["OREB"] + games["OREB_other"])) * (games["FGA"] - games["FGM"]) + games["TOV"]) + games["FGA_other"] + 0.4*games["FTA_other"] - 1.07 * (games["OREB_other"] / (games["OREB_other"] + games["DREB"])) * (games["FGA_other"] - games["FGM_other]) + games["TOV_other"]))

# ***Placeholder POSS***
games['POSS'] = 0.96*((games['FGA']) + games['TOV'] + 0.44 * games['FTA'] - games['OREB'])
games['OPP_POSS'] = 0.96*((games['OPP_FGA']) + games['OPP_TOV'] + 0.44 * games['OPP_FTA'] - games['OPP_OREB'])

# Steals Percentage
games['STL%'] = (games['STL'] / games['OPP_POSS'])
games['OPP_STL%'] = (games['OPP_STL'] / games['POSS'])

# Free Throw Rate
games['FTR'] = games['FTM'] / games['FGA']
games['OPP_FTR'] = games['OPP_FTM'] / games['OPP_FGA']

# True Shooting (Requires True Shooting Attempts)
tsa = games['FGA'] + 0.44 * games['FTA']
OPP_tsa = games['OPP_FGA'] + 0.44 * games['OPP_FTA']
games['TS'] = games['PTS'] / (2 * tsa)
games['OPP_TS'] = games['OPP_PTS'] / (2 * OPP_tsa)

# Assist Rate
games['ASTR'] = games['AST'] / (games['FGA'] + (.44 * games['FTA']) + games['AST'] + games['TOV'])
games['OPP_ASTR'] = games['OPP_AST'] / (games['OPP_FGA'] + (.44 * games['OPP_FTA']) + games['OPP_AST'] + games['OPP_TOV'])

# Total Rebound Percentage
games['TRB%'] = (games['REB'] * (games['REB'] / 5)) / (games['MIN'] * (games['REB'] + games['OPP_REB']))
games['OPP_TRB%'] = (games['OPP_REB'] * (games['OPP_REB'] / 5)) / (games['MIN'] * (games['OPP_REB'] + games['REB']))

# PACE
games['PACE'] = 48 * (games['POSS'] + games['OPP_POSS']) / (2 * (games['MIN'] / 5))
games['OPP_PACE'] = 48 * (games['OPP_POSS'] + games['POSS']) / (2 * (games['MIN'] / 5))

# Offensive Rating
games['ORTG'] = (games['PTS'] / games['POSS'])
games['OPP_ORTG'] = (games['OPP_PTS'] / games['OPP_POSS'])

# Defensive Rating
games['DRTG'] = (games['OPP_PTS'] / games['POSS'])
games['OPP_DRTG'] = (games['PTS'] / games['OPP_POSS'])

games.head()

,TEAM_ID,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PLUS_MINUS,MIN,EFG%,OPP_EFG%,BLK%,OPP_BLK%,TOV%,OPP_TOV%,ORB%,OPP_ORB%,DREB%,OPP_DREB%,POSS,OPP_POSS,STL%,OPP_STL%,FTR,OPP_FTR,TS,OPP_TS,ASTR,OPP_ASTR,TRB%,OPP_TRB%,PACE,OPP_PACE,ORTG,OPP_ORTG,DRTG,OPP_DRTG
29,1610612737,98,33,75,0.440,7,24,0.292,25,30,0.833,9,37,46,17,8,2,17,19,2.0,96,35,83,0.422,14,37,0.378,12,15,0.800,7,32,39,28,10,7,17,29,-2.0,238,0.486667,0.506024,0.043478,0.137255,0.161597,0.159475,0.219512,0.159091,0.840909,0.780488,92.352,95.616,0.083668,0.108281,0.333333,0.144578,0.555556,0.535714,0.139116,0.208024,0.020919,0.015037,94.773782,94.773782,1.061157,1.004016,1.039501,1.024933
53,1610612737,103,33,74,0.446,11,26,0.423,26,36,0.722,5,43,48,21,8,5,16,23,10.0,93,32,84,0.381,7,27,0.259,22,31,0.710,6,38,44,15,8,7,13,26,-10.0,240,0.52027,0.422619,0.087719,0.145833,0.151172,0.117498,0.116279,0.122449,0.877551,0.883721,96.8064,100.4544,0.079638,0.082639,0.351351,0.261905,0.573241,0.476239,0.165563,0.119389,0.02087,0.017536,98.6304,98.6304,1.063979,0.925793,0.96068,1.025341
102,1610612737,100,32,78,0.410,11,31,0.355,25,29,0.862,3,45,48,24,10,4,16,26,14.0,86,27,82,0.329,4,20,0.200,28,36,0.778,11,39,50,17,9,2,18,25,-14.0,240,0.480769,0.353659,0.064516,0.042553,0.149869,0.155387,0.071429,0.196429,0.803571,0.928571,99.6096,100.6464,0.099358,0.090353,0.320513,0.341463,0.550903,0.439493,0.183542,0.127974,0.019592,0.021259,100.128,100.128,1.003919,0.854477,0.863371,0.993578
119,1610612737,91,31,84,0.369,9,28,0.321,20,24,0.833,9,40,49,18,9,7,15,14,7.0,84,31,85,0.365,9,33,0.273,13,17,0.765,8,41,49,18,8,6,18,19,-7.0,241,0.422619,0.417647,0.134615,0.107143,0.136911,0.162925,0.18,0.166667,0.833333,0.82,96.5376,98.3808,0.091481,0.082869,0.238095,0.152941,0.481176,0.454152,0.14111,0.1401,0.020332,0.020332,97.054805,97.054805,0.942638,0.853825,0.870127,0.924977
142,1610612737,92,33,75,0.440,6,22,0.273,20,22,0.909,8,36,44,23,6,9,22,24,-9.0,101,36,92,0.391,10,30,0.333,19,25,0.760,15,29,44,26,8,2,13,16,9.0,240,0.48,0.445652,0.145161,0.037736,0.206224,0.112069,0.216216,0.294118,0.705882,0.783784,94.7328,96.96,0.061881,0.084448,0.266667,0.206522,0.543222,0.490291,0.17736,0.183099,0.018333,0.018333,95.8464,95.8464,0.971153,1.041667,1.066157,0.948845

In [6]:
# Z score normalization
realcols = list(games.columns.values)
for col in realcols:
   mean = games[col].mean()
   std = games[col].std()
   games[col] = (games[col] - mean)/std

In [7]:
# Test/Train splitting
from sklearn.metrics import r2_score
gamesPlusMinus = games["PLUS_MINUS"]
y = gamesPlusMinus.values
games = games.drop(columns=['PLUS_MINUS', 'OPP_PLUS_MINUS'])
x = games.values
print(x.shape)
print(y.shape)
xtrain, xtest, ytrain, ytest =  train_test_split(x,y, test_size = 0.2, random_state=1)

(17904, 66)
(17904,)

In [52]:
# Ridge Model
ridge = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1])
ridge.fit(xtrain, ytrain)

predict = ridge.predict(xtest)

#stats for the model
pd.set_option('display.max_rows', None)
#print(pd.Series(ridge.coef_, index = games.columns[0:66])) 
print(predict)
print(ytest)
mse = mean_squared_error(ytest, predict) 
print("Test mean squared error (MSE): {:.2f}".format(mse))
print("Score:", ridge.score(xtest,ytest))

TypeError: __init__() got an unexpected keyword argument 'random_state'

In [48]:
# LASSO
lasso = LassoCV(cv=5, random_state=0)
lasso.fit(xtrain, ytrain)

predict3 = lasso.predict(xtest)

#stats for the model
pd.set_option('display.max_rows', None)
#print(pd.Series(lasso.coef_, index = games.columns[0:66])) 
mse = mean_squared_error(ytest, predict3) 
print("Test mean squared error (MSE): {:.2f}".format(mse))
print("Score:", lasso.score(xtest,ytest))

Test mean squared error (MSE): 0.00
Score: 0.9954309696915028

In [9]:
# Visualization

In [10]:
#Adding Rolling averages to emulate how a team settles/grows in ability during a season/seasons
#games_averages = pd.concat([games.rolling(5).mean() for _, d in games.groupby('TEAM_ID')])
games_averages = games_averages.groupby('TEAM_ID')
games_averages = games_averages.rolling(5).mean()
games_averages = games_averages.reset_index(drop=True)
gamesPlusMinus = games_averages["PLUS_MINUS"]
#games_averages = games_averages.drop(columns=['PLUS_MINUS', 'OPP_PLUS_MINUS'])

# Converting entire DF to numeric
games_averages = games_averages.apply(pd.to_numeric, errors='coerce')

# Print Head
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_columns', None)
games_averages.head(30)

,FG_PCT,FG3_PCT,FT_PCT,PLUS_MINUS,OPP_FG_PCT,OPP_FG3_PCT,OPP_FT_PCT,OPP_PLUS_MINUS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.42,0.33,0.83,4.80,0.38,0.29,0.76,-4.80
5,0.41,0.34,0.79,4.20,0.36,0.27,0.74,-4.20
6,0.40,0.33,0.82,-3.40,0.39,0.30,0.77,3.40
7,0.42,0.32,0.77,-2.00,0.40,0.30,0.73,2.00
8,0.42,0.32,0.81,-5.60,0.41,0.30,0.74,5.60
9,0.43,0.29,0.76,-2.60,0.42,0.30,0.76,2.60
10,0.44,0.31,0.77,-3.40,0.43,0.29,0.79,3.40
11,0.44,0.31,0.77,3.60,0.42,0.28,0.71,-3.60
12,0.43,0.30,0.78,0.80,0.42,0.31,0.76,-0.80
13,0.44,0.29,0.72,6.20,0.39,0.28,0.76,-6.20
14,0.42,0.32,0.75,3.80,0.41,0.29,0.69,-3.80
15,0.43,0.31,0.76,8.00,0.40,0.30,0.67,-8.00
16,0.42,0.31,0.73,2.20,0.41,0.31,0.72,-2.20
17,0.43,0.32,0.75,2.48,0.42,0.28,0.68,-3.20
18,0.41,0.32,0.76,-3.52,0.46,0.33,0.67,2.80
19,0.43,0.32,0.73,0.48,0.43,0.30,0.69,-1.20
20,0.42,0.33,0.71,-4.72,0.45,0.31,0.70,4.00
21,0.42,0.32,0.70,-4.12,0.43,0.28,0.71,3.40
22,0.45,0.33,0.68,-5.20,0.46,0.32,0.76,5.20
23,0.46,0.33,0.73,-3.60,0.46,0.28,0.74,3.60
24,0.46,0.35,0.72,-11.20,0.48,0.32,0.78,11.20
25,0.44,0.33,0.76,-11.00,0.46,0.31,0.76,11.00
26,0.45,0.32,0.75,-13.80,0.47,0.34,0.76,13.80
27,0.41,0.30,0.77,-13.60,0.44,0.31,0.74,13.60
28,0.40,0.31,0.67,-16.00,0.42,0.33,0.76,16.00
29,0.38,0.31,0.71,-12.00,0.43,0.31,0.73,12.00

In [11]:
# games DF will now have the average stats of a teams most recent 10 games
#games = games_averages

# # Normalize Data




# Sending data to CSV
games.to_csv('games.csv', index = False)
games_averages.to_csv('games_averages.csv', index = False)d

# Print head
pd.set_option('display.max_columns', None)
games.head()

SyntaxError: invalid syntax (<ipython-input-11-8080587ff101>, line 14)