In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split

from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams

# Gets the box score of every single game (NBA + WNBA + others: nba.com doesn't seperate the leagues) 
# from 2014-2021 into a dataframe.
all_games_finder = leaguegamefinder.LeagueGameFinder()
all_games = all_games_finder.get_data_frames()[0]

# Creates empty dataframe with the same column names passed in from the dataframe containing all the games.
games = pd.DataFrame(all_games)

# Appends every game containing an NBA team in the all_games df to the games df. 
# Note: this double loop might legit get us 50% off... need to come up with a better implementation lmao. 
# It takes like 10 minutes... 
#nba_teams = teams.get_teams()
#for team in nba_teams:
#    temp_id = team['id']
#    for index, row in all_games.iterrows():
#        if row['TEAM_ID'] == temp_id:
#            games = games.append(row, ignore_index = True)
games.columns
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,52021,1612709893,CLC,Cleveland Charge,2052100050,2021-11-16,CLC @ FWN,L,242,96,...,0.556,8,34,42,20,5,4,19,15,-19.0
1,52021,1612709910,FWN,Fort Wayne Mad Ants,2052100050,2021-11-16,FWN vs. CLC,W,240,115,...,0.429,18,48,66,30,12,2,18,23,19.0
2,22021,1610612751,BKN,Brooklyn Nets,0022100210,2021-11-16,BKN vs. GSW,L,240,99,...,0.778,9,29,38,21,12,2,11,23,-18.0
3,22021,1610612744,GSW,Golden State Warriors,0022100210,2021-11-16,GSW @ BKN,W,241,117,...,0.786,9,44,53,25,4,8,21,27,18.0
4,52021,1612709918,TEX,Texas Legends,2052100051,2021-11-16,TEX @ MHU,L,240,100,...,0.900,14,40,54,13,16,6,14,18,-2.4

In [2]:
#This assumes Min is minutes played for each team
#sort the columns to pair each game with the two teams
games = games.sort_values(by=['GAME_ID'])

gamesteam1 = games[games.index % 2 == 0]
gamesteam2 = games[games.index % 2 == 1]

gamesteam1 = gamesteam1.reset_index(drop=True)
gamesteam2 = gamesteam2.reset_index(drop=True)

games = gamesteam1.join(gamesteam2, rsuffix='_other')
games.drop(columns=['SEASON_ID_other', 'GAME_DATE_other'])

['SEASON_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'TEAM_NAME',
 'GAME_ID',
 'GAME_DATE',
 'MATCHUP',
 'WL',
 'MIN',
 'PTS',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PLUS_MINUS',
 'SEASON_ID_other',
 'TEAM_ID_other',
 'TEAM_ABBREVIATION_other',
 'TEAM_NAME_other',
 'GAME_ID_other',
 'GAME_DATE_other',
 'MATCHUP_other',
 'WL_other',
 'MIN_other',
 'PTS_other',
 'FGM_other',
 'FGA_other',
 'FG_PCT_other',
 'FG3M_other',
 'FG3A_other',
 'FG3_PCT_other',
 'FTM_other',
 'FTA_other',
 'FT_PCT_other',
 'OREB_other',
 'DREB_other',
 'REB_other',
 'AST_other',
 'STL_other',
 'BLK_other',
 'TOV_other',
 'PF_other',
 'PLUS_MINUS_other']

In [6]:
#Brett Owen feature chunk
#STLP = Steal Percentage = 100 * (steals * (team's minutes played / 5)) / (minutes played * opp possessions)
#games["STLP"]

games["BLKP"] = 100 * (games["BLK"] * (games["MIN"]/5))/ (games["MIN"] * (games["FGA_other"] )) # need to subtract fga other by 3 point shot attempts
print(games)

      SEASON_ID     TEAM_ID TEAM_ABBREVIATION             TEAM_NAME  \
0         12015  1610612743               DEN        Denver Nuggets
1         12015  1610612766               CHA     Charlotte Hornets
2         12015  1610612754               IND        Indiana Pacers
3         12015  1610612762               UTA             Utah Jazz
4         12015  1610612747               LAL    Los Angeles Lakers
...         ...         ...               ...                   ...
14995     52021  1612709918               TEX         Texas Legends
14996     72021  1612709930               GLI       G League Ignite
14997     72021  1612709904               SXF  Sioux Falls Skyforce
14998     72021  1612709902               SCW   Santa Cruz Warriors
14999     32019  1610616833               GNS          Team Giannis

          GAME_ID   GAME_DATE      MATCHUP WL  MIN  PTS  ...  OREB_other  \
0      0011500001  2015-10-02    DEN @ LAC  L  240   96  ...           9
1      0011500002  2015-10-03    CHA @ ORL  W  241  106  ...          12
2      0011500003  2015-10-03  IND vs. NOP  L  241  105  ...          19
3      0011500004  2015-10-04    UTA @ LAL  W  240   90  ...           5
4      0011500004  2015-10-04  LAL vs. UTA  L  238   71  ...           7
...           ...         ...          ... ..  ...  ...  ...         ...
14995  2052100051  2021-11-16    TEX @ MHU  L  240  100  ...          16
14996  2072100001  2021-10-29    GLI @ IWA  L  239   87  ...          10
14997  2072100002  2021-10-31  SXF vs. GLI  W  240  104  ...           7
14998  2072100013  2021-11-03  SCW vs. GLI  W  239  110  ...          14
14999  2531900001  2020-01-23  GNS vs. LBN  L  190  139  ...          16

       DREB_other  REB_other  AST_other  STL_other  BLK_other  TOV_other  \
0              30         39         22         12          6         13
1              33         45         22         11          3         12
2              36         55         16          9          3         11
3              28         33         16          6          3         24
4              45         52         13          7          1         16
...           ...        ...        ...        ...        ...        ...
14995          44         60         19          7         17         20
14996          36         46         21         10          4         20
14997          38         45         23          8          5         27
14998          28         42         15         14          1         14
14999          36         52         33          6          2          8

       PF_other  PLUS_MINUS_other      BLKP
0            15               7.0  0.439560
1            30              -6.0  0.449438
2            22               5.0  3.106796
3            29             -20.0  1.126761
4            19              13.0  1.621622
...         ...               ...       ...
14995        16               6.4  1.212121
14996        29              11.0  0.722892
14997        17             -14.0  0.666667
14998        18             -19.6  1.956522
14999         7               0.0  0.180180

[15000 rows x 57 columns]